### ISSUE TITLE
Finish supporting To-Do playlists

### ISSUE THREAD

**Issue by loafofpiecrust** [loafofpiecrust/turntable#46]
- [ ] Playlist adapter
- [ ] Track is "completed" when it's been listened to since the creation of the playlist.
- [ ] Consider adding `listenCount` and `lastListenTime` as saved metadata associated with songs. Problem: this keeps expanding a ridiculous amount as you listen to more music.
- [ ] Album is "completed" when all of its tracks are considered "completed"

**Comment by loafofpiecrust** [comment]
Seems convoluted.
